SELECT UNIVERSITY,
	CAREER,
	INSCRIPTION_DATE,
	NOMBRE AS LAST_NAME,
	SEXO AS GENDER,
	BIRTH_DATE AS AGE,   
	NULL AS POSTAL_CODE,
	LOCATION,
	EMAIL
FROM JUJUY_UTN
WHERE INSCRIPTION_DATE BETWEEN '2020/09/01' AND '2021/02/01'
	AND UNIVERSITY = 'universidad nacional de jujuy';