SELECT JUJUY_UTN.UNIVERSITY,
	JUJUY_UTN.CAREER,
	JUJUY_UTN.INSCRIPTION_DATE,
	JUJUY_UTN.NOMBRE AS LAST_NAME,
	JUJUY_UTN.SEXO AS GENDER,
	JUJUY_UTN.BIRTH_DATE,
	NULL AS AGE,
	NULL AS POSTAL_CODE,
	JUJUY_UTN.LOCATION,
	JUJUY_UTN.EMAIL
FROM PUBLIC.JUJUY_UTN
WHERE INSCRIPTION_DATE BETWEEN '2020/09/01' AND '2021/02/01'
	AND UNIVERSITY = 'universidad nacional de jujuy';