SELECT UNIVERSIDAD AS UNIVERSITY,
	CAREERS AS CAREER,
	FECHA_DE_INSCRIPCION AS INSCRIPTION_DATE,
	NAMES AS LAST_NAME,
	SEXO AS GENDER,
	BIRTH_DATES AS AGE,
	CODIGO_POSTAL AS POSTAL_CODE,
	NULL AS LOCATION,
	CORREOS_ELECTRONICOS AS EMAIL
FROM PALERMO_TRES_DE_FEBRERO
WHERE UNIVERSIDAD = '_universidad_de_palermo'
	AND TO_DATE(FECHA_DE_INSCRIPCION,'DD/Mon/YY') BETWEEN '01/Sep/20' AND '01/Feb/21';